# -*- coding: utf-8 -*-
print("Mark Joseph R. Largo")
print("Laylay, Boac, Marinduque")
print("January 5, 2003")
print("Marinduque State College")
print("BS Information Technology")
print("2nd Year")
print("Section 2A")
print("Playing Badminton")
print("Playing Video Games")
print("Watching Movies")
print("Listening to Music")
print("Photography")